/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransformationStoriesRouteImport } from './routes/transformation-stories'
import { Route as TransformationJourneyRouteImport } from './routes/transformation-journey'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessEnginesRouteImport } from './routes/business-engines'
import { Route as AiProductsRouteImport } from './routes/ai-products'
import { Route as AiAssessmentRouteImport } from './routes/ai-assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TransformationStoriesRoute = TransformationStoriesRouteImport.update({
  id: '/transformation-stories',
  path: '/transformation-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationJourneyRoute = TransformationJourneyRouteImport.update({
  id: '/transformation-journey',
  path: '/transformation-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEnginesRoute = BusinessEnginesRouteImport.update({
  id: '/business-engines',
  path: '/business-engines',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProductsRoute = AiProductsRouteImport.update({
  id: '/ai-products',
  path: '/ai-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssessmentRoute = AiAssessmentRouteImport.update({
  id: '/ai-assessment',
  path: '/ai-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/ai-products': typeof AiProductsRoute
  '/business-engines': typeof BusinessEnginesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/transformation-journey': typeof TransformationJourneyRoute
  '/transformation-stories': typeof TransformationStoriesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/ai-products': typeof AiProductsRoute
  '/business-engines': typeof BusinessEnginesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/transformation-journey': typeof TransformationJourneyRoute
  '/transformation-stories': typeof TransformationStoriesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/ai-products': typeof AiProductsRoute
  '/business-engines': typeof BusinessEnginesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/transformation-journey': typeof TransformationJourneyRoute
  '/transformation-stories': typeof TransformationStoriesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-assessment'
    | '/ai-products'
    | '/business-engines'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/mcp'
    | '/roi-calculator'
    | '/transformation-journey'
    | '/transformation-stories'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assessment'
    | '/ai-products'
    | '/business-engines'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/mcp'
    | '/roi-calculator'
    | '/transformation-journey'
    | '/transformation-stories'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-assessment'
    | '/ai-products'
    | '/business-engines'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/mcp'
    | '/roi-calculator'
    | '/transformation-journey'
    | '/transformation-stories'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAssessmentRoute: typeof AiAssessmentRoute
  AiProductsRoute: typeof AiProductsRoute
  BusinessEnginesRoute: typeof BusinessEnginesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  McpRoute: typeof McpRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  TransformationJourneyRoute: typeof TransformationJourneyRoute
  TransformationStoriesRoute: typeof TransformationStoriesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transformation-stories': {
      id: '/transformation-stories'
      path: '/transformation-stories'
      fullPath: '/transformation-stories'
      preLoaderRoute: typeof TransformationStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation-journey': {
      id: '/transformation-journey'
      path: '/transformation-journey'
      fullPath: '/transformation-journey'
      preLoaderRoute: typeof TransformationJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-engines': {
      id: '/business-engines'
      path: '/business-engines'
      fullPath: '/business-engines'
      preLoaderRoute: typeof BusinessEnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-products': {
      id: '/ai-products'
      path: '/ai-products'
      fullPath: '/ai-products'
      preLoaderRoute: typeof AiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assessment': {
      id: '/ai-assessment'
      path: '/ai-assessment'
      fullPath: '/ai-assessment'
      preLoaderRoute: typeof AiAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAssessmentRoute: AiAssessmentRoute,
  AiProductsRoute: AiProductsRoute,
  BusinessEnginesRoute: BusinessEnginesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  McpRoute: McpRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  TransformationJourneyRoute: TransformationJourneyRoute,
  TransformationStoriesRoute: TransformationStoriesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
